### ISSUE TITLE
myodoo-docker/Dockerfiles/myodoo-10-public/odoo.conf

### ISSUE THREAD

**Issue by axpdreamer** [equitania/myodoo-docker#2]
Password and Username should be "myodoo10", to work with the default pg-config

**Comment by eqms** [comment]
Thanks for the tip, but I change now all to "myodoo" only - also in the odoo.conf.

**Comment by axpdreamer** [comment]
Please also update docker hub readme. TiA

**Comment by eqms** [comment]
Thanks for the tip - Done.
