### ISSUE TITLE
Falsches PostreSQL APT Repo in Dockerfile

### ISSUE THREAD

**Issue by debalance** [equitania/myodoo-docker#3]
Da sollte vermutlich `buster` anstatt `stretch` stehen: https://github.com/equitania/myodoo-docker/blob/master/Dockerfiles/prepare-myodoo-v12/Dockerfile#L22

Die anderen Dockerfiles habe ich nicht geprüft.

**Comment by eqms** [comment]
Korrigiert. Danke für den Hinweis.
