### ISSUE TITLE
odoo-ce.zip missing

### ISSUE THREAD

**Issue by LeoWinterDE** [equitania/myodoo-docker#3]
My build fails because the odoo-ce.zip file is missing. Where do i find the odoo-ce.zip file? I want to build a small docker file with alpine linux, and a docker compose file (myodoo and database) for the simple use of myodoo.

```
# git clone https://github.com/equitania/myodoo-docker.git
# cd myodoo-docker/Dockerfiles/myodoo-10-public/
# docker build -t myodoo/myodoo-10-public:171002 .
```
Fails with odoo-ce.zip missing, like
```
Step 8/20 : COPY odoo-ce.zip /opt/odoo/odoo-server/
COPY failed: stat /var/lib/docker/tmp ... /odoo-ce.zip: no such file or directory
```

**Comment by eqms** [comment]
Use on of our ready tags: https://hub.docker.com/r/myodoo/myodoo-10-public/tags/ or build our own zip f.e.

mkdir /home/ownerp/Public/tmp
mkdir /home/ownerp/Public/tmp/addons
rm /home/ownerp/Public/odoo-ce.zip
cp -r /home/ownerp/Public/gitbase/myodoo-server-10/odoo /home/ownerp/Public/tmp
cp -r /home/ownerp/Public/gitbase/myodoo-server-10/addons/* /home/ownerp/Public/tmp/addons
cp -r /home/ownerp/Public/gitbase/myodoo-addons-v10/eq_* /home/ownerp/Public/tmp/addons
cp -r /home/ownerp/Public/gitbase/myodoo-addons-v10/prag* /home/ownerp/Public/tmp/addons
cp -r /home/ownerp/Public/gitbase/myodoo-addons-v10/sys* /home/ownerp/Public/tmp/addons
cp -r /home/ownerp/Public/gitbase/myodoo-oca-v10/3rd-party/* /home/ownerp/Public/tmp/addons
cp -r /home/ownerp/Public/gitbase/myodoo-oca-v10/banking/* /home/ownerp/Public/tmp/addons
cp -r /home/ownerp/Public/gitbase/myodoo-oca-v10/contract/* /home/ownerp/Public/tmp/addons
cp -r /home/ownerp/Public/gitbase/myodoo-oca-v10/crm/* /home/ownerp/Public/tmp/addons
cp -r /home/ownerp/Public/gitbase/myodoo-oca-v10/hr/* /home/ownerp/Public/tmp/addons
cp -r /home/ownerp/Public/gitbase/myodoo-oca-v10/hr-timesheet/* /home/ownerp/Public/tmp/addons
cp -r /home/ownerp/Public/gitbase/myodoo-oca-v10/knowledge/* /home/ownerp/Public/tmp/addons
cp -r /home/ownerp/Public/gitbase/myodoo-oca-v10/partner-contact/* /home/ownerp/Public/tmp/addons
cp -r /home/ownerp/Public/gitbase/myodoo-oca-v10/product-attribute/* /home/ownerp/Public/tmp/addons
cp -r /home/ownerp/Public/gitbase/myodoo-oca-v10/project/* /home/ownerp/Public/tmp/addons
cp -r /home/ownerp/Public/gitbase/myodoo-oca-v10/purchase-workflow/* /home/ownerp/Public/tmp/addons
cp -r /home/ownerp/Public/gitbase/myodoo-oca-v10/reporting-engine/* /home/ownerp/Public/tmp/addons
cp -r /home/ownerp/Public/gitbase/myodoo-oca-v10/sale-workflow/* /home/ownerp/Public/tmp/addons
cp -r /home/ownerp/Public/gitbase/myodoo-oca-v10/server-tools/* /home/ownerp/Public/tmp/addons
cp -r /home/ownerp/Public/gitbase/myodoo-oca-v10/social/* /home/ownerp/Public/tmp/addons
cp -r /home/ownerp/Public/gitbase/myodoo-oca-v10/web/* /home/ownerp/Public/tmp/addons
cp -r /home/ownerp/Public/gitbase/myodoo-oca-v10/website/* /home/ownerp/Public/tmp/addons

**Comment by LeoWinterDE** [comment]
So your [ReadMe.md](https://github.com/equitania/myodoo-docker/blob/master/Dockerfiles/myodoo-10-public/ReadMe.md) is wrong? `docker build -t myodoo/myodoo-10-public:171201 .`

> Use on of our ready tags: https://hub.docker.com/r/myodoo/myodoo-10-public/tags/

The image is about 1,3GB, i want to minimize this with alpine. And your docker hub image doesn't work with docker-compose, because the zip is missing.

The zip only contains the empty directories? Where are the Odoo Server files coming from? Why aren't they being built from the git source?

**Comment by eqms** [comment]
The size depends not this image. It depends on the prepare image.
[Prepare](https://hub.docker.com/r/myodoo/prepare-v10/tags/ )

Sources:
[https://github.com/equitania/myodoo-server-10](https://github.com/equitania/myodoo-server-10)
[https://github.com/equitania/myodoo-addons-v10](https://github.com/equitania/myodoo-addons-v10)
[https://github.com/equitania/myodoo-oca-v10](https://github.com/equitania/myodoo-oca-v10)

**Comment by LeoWinterDE** [comment]
> The size depends not this image. It depends on the prepare image. Prepare

Yes i know.

So then the release is therefore rolling in its version (10) and without any major upgrades to the db?
Simply changing the container, with its odoo run files (not the UGC of course, which anyway belongs in a volume) to upgrade should be enough. I'll work on it...
